/* ARCHIVO: sql/01_ddl_estructura.sql
   DESCRIPCIÓN: Definición de tablas, restricciones y vistas.
   PROYECTO: Casino DB
*/

-- 1. BORRADO DE OBJETOS ANTERIORES (Limpieza)
DROP TABLE CLIENTE CASCADE CONSTRAINTS ;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS ;
DROP TABLE CASINO CASCADE CONSTRAINTS ;
DROP TABLE VIP CASCADE CONSTRAINTS;
DROP TABLE NORMAL CASCADE CONSTRAINTS ;
DROP TABLE TELEFONOS_CASINO CASCADE CONSTRAINTS ;
DROP TABLE SALA CASCADE CONSTRAINTS ;
DROP TABLE MESA_JUEGO CASCADE CONSTRAINTS ;
DROP TABLE CRUPIER CASCADE CONSTRAINTS ;
DROP TABLE EMPLEADO_RECEPCION CASCADE CONSTRAINTS ;
DROP TABLE EMPLEADO_ADMINISTRACION CASCADE CONSTRAINTS ;
DROP TABLE JUEGO CASCADE CONSTRAINTS ;
DROP TABLE APUESTA CASCADE CONSTRAINTS ;
DROP TABLE TORNEO CASCADE CONSTRAINTS ;
DROP TABLE RONDA_TORNEO CASCADE CONSTRAINTS ;
DROP TABLE SEGURATA_SUBCONTRATADO CASCADE CONSTRAINTS ;
DROP TABLE MAQUINA_APUESTA CASCADE CONSTRAINTS ;
DROP TABLE MAQUINA_DEPORTIVA CASCADE CONSTRAINTS ;
DROP TABLE RULETA CASCADE CONSTRAINTS ;
DROP TABLE TRAGAPERRAS CASCADE CONSTRAINTS ;
DROP TABLE CASINO_ORGANIZA_TORNEO CASCADE CONSTRAINTS ;
DROP TABLE CLIENTE_JUEGO_MESA_APUESTA CASCADE CONSTRAINTS ;
DROP TABLE VIP_PARTICIPA_TORNEO CASCADE CONSTRAINTS ;
DROP TABLE CLIENTE_JUEGA_MAQUINA CASCADE CONSTRAINTS ;
DROP TABLE RECEPCION_PAGA_CLIENTE CASCADE CONSTRAINTS ;
DROP TABLE CASINO_TIENE_CLIENTE CASCADE CONSTRAINTS ;
DROP TABLE CASINO_CONTRATA_SUBSEG CASCADE CONSTRAINTS ;
DROP TABLE EMPLEADO_DE_SEGURIDAD CASCADE CONSTRAINTS ;
DROP TABLE EMPSEG_SUPERVISA_TORNEO CASCADE CONSTRAINTS ;
DROP TABLE EMPSEG_VIGILA_SALA CASCADE CONSTRAINTS ;
DROP TABLE SEGSUBCONTRATADO_VIGILA_SALA CASCADE CONSTRAINTS ;
DROP VIEW PREMIOS_PAGADOS;
DROP VIEW CLIENTE_APUESTAS ;
DROP VIEW TORNEOS_IMPORTANTES;
DROP VIEW MESAS_DISPONIBLES;

-- 2. CREACIÓN DE TABLAS

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(8),
    NOMBRE VARCHAR2(50) ,
    EDAD NUMBER(3) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL, 
    DNI VARCHAR2(9) UNIQUE NOT NULL ,
    SALDO NUMBER(10,2) DEFAULT 0.0 NOT NULL, 
    PRIMARY KEY (ID_CLIENTE),
    CHECK (EDAD > 18)
);

CREATE TABLE CASINO 
(
    ID_CASINO NUMBER ( 8 )  , 
    NOMBRE VARCHAR2 ( 15 ) NOT NULL ,
    DIRECCION VARCHAR2 ( 10 ) NOT NULL , 
    EMAIL VARCHAR2 ( 30 ) NOT NULL ,
    PRIMARY KEY ( ID_CASINO ), 
    CHECK (EMAIL LIKE '%_@__%.__%')
); 

CREATE TABLE EMPLEADO 
(
    NSS VARCHAR2 ( 12 )  ,
    DNI VARCHAR2 ( 9 ) UNIQUE NOT NULL , 
    NOMBRE VARCHAR2 ( 50 ) NOT NULL ,
    SALARIO  NUMBER ( 4 ) NOT NULL , 
    TIPO_CONTRATO VARCHAR2 ( 15 ) NOT NULL , 
    CASINO_TRABAJA NUMBER ( 8 ) , 
    FOREIGN KEY ( CASINO_TRABAJA ) REFERENCES CASINO ( ID_CASINO ) ON DELETE SET NULL , 
    PRIMARY KEY ( NSS ) , 
    CHECK ( SALARIO > 1100 )
);

-- Alteración para referencia circular (Director es un Empleado)
ALTER TABLE CASINO ADD ( DIRECTOR VARCHAR2 (12)) ;
ALTER TABLE CASINO ADD CONSTRAINT FK_DIRECTOR FOREIGN KEY ( DIRECTOR ) REFERENCES EMPLEADO (NSS) ON DELETE SET NULL;

CREATE TABLE VIP 
(
    ID_VIP NUMBER ( 8 ),
    FECHA_INSCRIPCION DATE NOT NULL ,
    REGIMEN_VIP VARCHAR2 ( 10 ) NOT NULL , 
    EMPLEADO_INSCRIPCION VARCHAR2 (12) ,
    FOREIGN KEY ( EMPLEADO_INSCRIPCION ) REFERENCES  EMPLEADO ( NSS ) ON DELETE CASCADE ,
    FOREIGN KEY ( ID_VIP ) REFERENCES CLIENTE( ID_CLIENTE ) ON DELETE CASCADE ,
    PRIMARY KEY ( ID_VIP )  
);

CREATE TABLE NORMAL 
(
    ID_NORMAL NUMBER ( 8 ),   
    FOREIGN KEY ( ID_NORMAL ) REFERENCES CLIENTE ( ID_CLIENTE ) ON DELETE CASCADE ,
    PRIMARY KEY ( ID_NORMAL )
);

CREATE TABLE TELEFONOS_CASINO 
(
    ID_CASINO NUMBER ( 8 ), 
    TELEFONO NUMBER ( 9 ) , 
    FOREIGN KEY ( ID_CASINO ) REFERENCES CASINO( ID_CASINO  ) ON DELETE CASCADE ,
    PRIMARY KEY ( ID_CASINO , TELEFONO )
) ; 

CREATE TABLE SALA 
(
    ID_SALA NUMBER ( 8 ) , 
    NOMBRE VARCHAR2 ( 20 ) NOT NULL, 
    LOCALIZACION VARCHAR2 ( 10 ) NOT NULL , 
    CAPACIDAD NUMBER ( 4 ) NOT NULL, 
    CASINO_PERTENECE NUMBER ( 8 ) , 
    FOREIGN KEY (CASINO_PERTENECE ) REFERENCES CASINO ( ID_CASINO ) , 
    PRIMARY KEY ( ID_SALA ) 
);

CREATE TABLE MESA_JUEGO 
(
    ID_MESA NUMBER ( 8 )  ,
    TIPO_JUEGO VARCHAR2 ( 20 ) NOT NULL ,
    CAPACIDAD  NUMBER ( 3 ) NOT NULL , 
    ESTADO VARCHAR2 ( 20 ) NOT NULL , 
    ID_SALA NUMBER ( 8 ) NOT NULL , 
    FOREIGN KEY ( ID_SALA ) REFERENCES SALA ( ID_SALA ) ON DELETE SET NULL , 
    PRIMARY KEY ( ID_MESA ) , 
    CHECK ( CAPACIDAD > 4 )
);

CREATE TABLE CRUPIER 
(
    NSS VARCHAR2 ( 12 ) , 
    MESA_ASIGNADA NUMBER ( 8 ) NOT NULL , 
    SUPLENTE VARCHAR2 ( 12 )   , 
    FOREIGN KEY ( MESA_ASIGNADA ) REFERENCES MESA_JUEGO  ( ID_MESA)  ON DELETE SET NULL ,   
    FOREIGN KEY ( SUPLENTE ) REFERENCES CRUPIER( NSS ) ON DELETE SET NULL,
    FOREIGN KEY ( NSS ) REFERENCES EMPLEADO ( NSS ) ON DELETE CASCADE , 
    PRIMARY KEY ( NSS ) 
);

CREATE TABLE EMPLEADO_RECEPCION 
(
    NSS VARCHAR2 ( 12 )  , 
    PUESTO NUMBER ( 4 ) NOT NULL , 
    FOREIGN KEY ( NSS ) REFERENCES EMPLEADO ( NSS ) ON DELETE CASCADE , 
    PRIMARY KEY ( NSS ) 
); 

CREATE TABLE EMPLEADO_ADMINISTRACION 
(
    NSS VARCHAR2 ( 16 )  ,    
    USUARIO VARCHAR2 ( 10 ) NOT NULL , 
    CLAVE VARCHAR2 (12) NOT NULL , 
    FOREIGN KEY ( NSS ) REFERENCES EMPLEADO ( NSS ) ON DELETE CASCADE , 
    PRIMARY KEY ( NSS ) 
); 

CREATE TABLE JUEGO 
(
    ID_JUEGO NUMBER ( 8 ) ,
    FECHA DATE NOT NULL ,
    NUM_PARTICIPANTES NUMBER ( 3 ) NOT NULL ,
    EN_QUE_MESA NUMBER ( 8 ) NOT NULL , 
    FOREIGN KEY ( EN_QUE_MESA ) REFERENCES MESA_JUEGO ( ID_MESA ) ON DELETE CASCADE , 
    PRIMARY KEY ( ID_JUEGO ) , 
    CHECK ( NUM_PARTICIPANTES > 2 )
); 

CREATE TABLE APUESTA(
    RESULTADO VARCHAR2( 8 ) NOT NULL,
    ID_APUESTA NUMBER ( 8 )  , 
    VALOR NUMBER ( 5,2 ) NOT NULL,
    DESCRIPCION VARCHAR2 ( 15 ) , 
    EN_QUE_JUEGO NUMBER ( 8 ) NOT NULL , 
    FOREIGN KEY ( EN_QUE_JUEGO) REFERENCES JUEGO ( ID_JUEGO) ON DELETE CASCADE, 
    PRIMARY KEY ( ID_APUESTA ) , 
    CHECK ( VALOR > 1.0 ) 
); 

CREATE TABLE TORNEO 
(
    ID_TORNEO NUMBER ( 8 ) , 
    PREMIO NUMBER (10,2) NOT NULL , 
    FECHA DATE NOT NULL , 
    DESCRIPCION VARCHAR2 ( 200 ) ,
    GANADOR NUMBER ( 8 ),
    PRIMARY KEY ( ID_TORNEO ),
    FOREIGN KEY ( GANADOR ) REFERENCES VIP ( ID_VIP ) ON DELETE CASCADE
); 

CREATE TABLE RONDA_TORNEO 
(
    ID_TORNEO NUMBER ( 8 ) , 
    RONDA_TORNEO NUMBER ( 8 ) ,
    FECHA_RONDA DATE NOT NULL , 
    DESCRIPCION_RONDA VARCHAR2 ( 50 ) , 
    FOREIGN KEY ( ID_TORNEO ) REFERENCES TORNEO ( ID_TORNEO) ON DELETE CASCADE, 
    PRIMARY KEY ( ID_TORNEO , RONDA_TORNEO)
);

CREATE TABLE SEGURATA_SUBCONTRATADO (
    CERT_SEG VARCHAR2 ( 40 )NOT NULL , 
    TURNO VARCHAR2 ( 10 ) NOT NULL , 
    NOMBRE VARCHAR2 ( 50 ) NOT NULL,
    DNI VARCHAR2 ( 9 )  ,
    PRIMARY KEY ( DNI ) 
);

CREATE TABLE EMPLEADO_DE_SEGURIDAD ( 
    NSS VARCHAR2 ( 12 ) , 
    DNI VARCHAR2 ( 9 )  , 
    FOREIGN KEY ( NSS ) REFERENCES EMPLEADO ( NSS ) ON DELETE CASCADE,  
    FOREIGN KEY ( DNI) REFERENCES SEGURATA_SUBCONTRATADO ( DNI) ON DELETE CASCADE,
    PRIMARY KEY ( NSS , DNI )
);

CREATE TABLE MAQUINA_APUESTA 
(
    NUMERO_SERIE VARCHAR2 ( 12 ) ,
    ID_SALA NUMBER ( 8) ,
    FOREIGN KEY  ( ID_SALA ) REFERENCES SALA ( ID_SALA) ON DELETE CASCADE , 
    PRIMARY KEY ( NUMERO_SERIE )  
);

CREATE TABLE MAQUINA_DEPORTIVA 
(
    DEPORTE VARCHAR2 ( 10 )  ,
    TIPO_APUESTA VARCHAR2 ( 12 )  ,
    NUM_SERIE VARCHAR2 ( 12 ) NOT NULL  , 
    FOREIGN KEY ( NUM_SERIE ) REFERENCES MAQUINA_APUESTA ( NUMERO_SERIE) ON DELETE CASCADE,
    PRIMARY KEY ( DEPORTE , TIPO_APUESTA )
);

CREATE TABLE RULETA (
    APUESTA_MIN NUMBER ( 3 )  , 
    APUESTA_MAX NUMBER ( 5 ) , 
    NUM_SERIE VARCHAR2 ( 12 ) NOT NULL , 
    FOREIGN KEY ( NUM_SERIE ) REFERENCES MAQUINA_APUESTA ( NUMERO_SERIE) ON DELETE CASCADE,
    PRIMARY KEY ( APUESTA_MIN,APUESTA_MAX ),
    CHECK (APUESTA_MIN < APUESTA_MAX)
);

CREATE TABLE TRAGAPERRAS (
    RTP NUMBER ( 5 ) , 
    ACUMULADO NUMBER ( 5) , 
    NUM_SERIE VARCHAR2 ( 12 ) NOT NULL , 
    FOREIGN KEY ( NUM_SERIE ) REFERENCES MAQUINA_APUESTA ( NUMERO_SERIE)ON DELETE CASCADE,
    PRIMARY KEY ( RTP ) 
); 

CREATE TABLE CASINO_ORGANIZA_TORNEO (
  ID_CASINO NUMBER ( 8 ) ,
  ID_TORNEO NUMBER ( 8 ) ,
  FOREIGN KEY ( ID_CASINO ) REFERENCES CASINO ( ID_CASINO ) ON DELETE CASCADE ,
  FOREIGN KEY ( ID_TORNEO ) REFERENCES TORNEO ( ID_TORNEO ) ON DELETE CASCADE,
  PRIMARY KEY ( ID_CASINO , ID_TORNEO ) 
);

CREATE TABLE CLIENTE_JUEGO_MESA_APUESTA (
	ID_CLIENTE NUMBER( 8 ) ,
	ID_MESA_JUEGO NUMBER ( 8 ) , 
	ID_APUESTA NUMBER ( 8 ) , 
    ID_JUEGO NUMBER ( 8 ) , 
	FOREIGN KEY ( ID_CLIENTE ) REFERENCES CLIENTE ( ID_CLIENTE ) ON DELETE CASCADE , 
	FOREIGN KEY ( ID_MESA_JUEGO ) REFERENCES MESA_JUEGO ( ID_MESA) ON DELETE CASCADE, 
	FOREIGN KEY ( ID_APUESTA ) REFERENCES APUESTA( ID_APUESTA )ON DELETE CASCADE , 
	FOREIGN KEY ( ID_JUEGO ) REFERENCES JUEGO( ID_JUEGO ) ON DELETE CASCADE, 
    PRIMARY KEY ( ID_CLIENTE ,ID_JUEGO , ID_MESA_JUEGO , ID_APUESTA ) 
);

CREATE TABLE VIP_PARTICIPA_TORNEO (
    ID_TORNEO NUMBER ( 8 ) , 
    ID_CLIENTE NUMBER ( 8 ) ,
    FOREIGN KEY (ID_TORNEO) REFERENCES TORNEO(ID_TORNEO)ON DELETE CASCADE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)ON DELETE CASCADE, 
    PRIMARY KEY (ID_TORNEO, ID_CLIENTE)
); 

CREATE TABLE CLIENTE_JUEGA_MAQUINA ( 
    NUMERO_SERIE VARCHAR2 ( 12 ) , 
    ID_CLIENTE NUMBER ( 8 ) , 
    DINERO NUMBER ( 5 , 2 ) NOT NULL , 
    FOREIGN KEY ( NUMERO_SERIE ) REFERENCES MAQUINA_APUESTA ( NUMERO_SERIE ) ON DELETE CASCADE , 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)ON DELETE CASCADE, 
    PRIMARY KEY ( NUMERO_SERIE , ID_CLIENTE ) 
) ;

CREATE TABLE RECEPCION_PAGA_CLIENTE ( 
    ID_PAGO NUMBER ( 8 ) , 
    ID_RECEP VARCHAR2 ( 12 ) , 
    ID_CLIENTE NUMBER ( 8 ) , 
    FECHA_PAGO DATE NOT NULL , 
    DINERO NUMBER ( 5,2 ) NOT NULL , 
    FOREIGN KEY ( ID_RECEP ) REFERENCES EMPLEADO_RECEPCION( NSS ) ON DELETE CASCADE, 
    FOREIGN KEY ( ID_CLIENTE ) REFERENCES CLIENTE( ID_CLIENTE ) ON DELETE CASCADE , 
    PRIMARY KEY ( ID_PAGO , ID_CLIENTE , ID_RECEP ) 
);

CREATE TABLE CASINO_TIENE_CLIENTE (
  ID_CASINO NUMBER ( 8 ) ,
  ID_CLIENTE NUMBER ( 8 ) ,  
  FOREIGN KEY (ID_CASINO) REFERENCES CASINO ( ID_CASINO) ON DELETE CASCADE , 
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE ( ID_CLIENTE) ON DELETE CASCADE , 
  PRIMARY KEY  ( ID_CLIENTE ,  ID_CASINO ) 
);

CREATE TABLE CASINO_CONTRATA_SUBSEG (
	CERT_SEG VARCHAR2 ( 40 ) , 
	ID_CASINO NUMBER ( 8 ) , 
    DNI VARCHAR2 ( 9 ) ,
	FOREIGN KEY ( DNI ) REFERENCES SEGURATA_SUBCONTRATADO ( DNI ) ON DELETE CASCADE,  
	FOREIGN KEY ( ID_CASINO ) REFERENCES CASINO ( ID_CASINO )ON DELETE CASCADE ,
	PRIMARY KEY ( ID_CASINO , DNI ) 
) ; 

CREATE TABLE EMPSEG_SUPERVISA_TORNEO (
	DNI VARCHAR2 ( 9 ) ,
    NSS VARCHAR2 ( 12 ) , 
	ID_TORNEO NUMBER ( 8 ) ,
	FOREIGN KEY ( DNI , NSS ) REFERENCES EMPLEADO_DE_SEGURIDAD ( DNI , NSS ) ON DELETE CASCADE,
    FOREIGN KEY ( ID_TORNEO ) REFERENCES TORNEO ( ID_TORNEO) ON DELETE CASCADE, 
    PRIMARY KEY ( NSS , DNI , ID_TORNEO)  
) ; 

CREATE TABLE EMPSEG_VIGILA_SALA (
    DNI VARCHAR2 ( 9 ) ,
    NSS VARCHAR2 ( 12 ) ,
    ID_SALA NUMBER ( 8 ) ,
    HORAS NUMBER ( 3 ),
    FOREIGN KEY ( DNI , NSS  ) REFERENCES EMPLEADO_DE_SEGURIDAD ( DNI , NSS  )ON DELETE CASCADE ,
    FOREIGN KEY ( ID_SALA ) REFERENCES SALA ( ID_SALA) ON DELETE CASCADE, 
    PRIMARY KEY ( DNI , NSS ,  ID_SALA)
);

CREATE TABLE SEGSUBCONTRATADO_VIGILA_SALA (
    DNI VARCHAR2 ( 9 ) ,
    ID_SALA NUMBER ( 8 ) , 
    HORAS NUMBER ( 3 ) ,
    FOREIGN KEY ( DNI ) REFERENCES SEGURATA_SUBCONTRATADO ( DNI )ON DELETE CASCADE ,
    FOREIGN KEY ( ID_SALA ) REFERENCES SALA ( ID_SALA) ON DELETE CASCADE, 
    PRIMARY KEY ( DNI , ID_SALA)
);

-- 3. VISTAS

CREATE OR REPLACE VIEW PREMIOS_PAGADOS
	AS SELECT T.PREMIO, C.NOMBRE, C.DNI, C.ID_CLIENTE, T.ID_TORNEO
		FROM VIP V, TORNEO T, CLIENTE C
		WHERE T.GANADOR = V.ID_VIP AND C.ID_CLIENTE = V.ID_VIP 
        ORDER BY 1;

CREATE OR REPLACE VIEW CLIENTE_APUESTAS	
    AS SELECT C.DNI,A.RESULTADO, A.VALOR, A.DESCRIPCION , A.ID_APUESTA
        FROM CLIENTE C, APUESTA A, CLIENTE_JUEGO_MESA_APUESTA X
        WHERE C.ID_CLIENTE = X.ID_CLIENTE AND A.ID_APUESTA=X.ID_APUESTA
        ORDER BY 1 , 2  ;
 
 CREATE OR REPLACE VIEW TORNEOS_IMPORTANTES 
    AS SELECT * FROM TORNEO 
    WHERE PREMIO > 10000
    ORDER BY PREMIO;

CREATE OR REPLACE VIEW MESAS_DISPONIBLES 
    AS SELECT * FROM MESA_JUEGO
    WHERE ESTADO='Disponible'
    ORDER BY TIPO_JUEGO ;