-- 1. Preparación
SET FOREIGN_KEY_CHECKS = 0;

-- 2. Borrado limpio
DROP TABLE IF EXISTS CLIENTE_REALIZA_APUESTA_MESA;
DROP TABLE IF EXISTS CASINO_TIENE_CLIENTE;
DROP TABLE IF EXISTS EMPLEADO_ADMINISTRACION;
DROP TABLE IF EXISTS APUESTA;
DROP TABLE IF EXISTS TRANSACCION_CAJA;
DROP TABLE IF EXISTS EMPLEADO_RECEPCION;
DROP TABLE IF EXISTS REGISTRO_CRUPIERS_SESIONES;
DROP TABLE IF EXISTS SESION_MESA;
DROP TABLE IF EXISTS CRUPIER;
DROP TABLE IF EXISTS MESA_JUEGO;
DROP TABLE IF EXISTS SALA;
DROP TABLE IF EXISTS VIP;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS CASINO;
DROP TABLE IF EXISTS CLIENTE;

SET FOREIGN_KEY_CHECKS = 1;

-- 3. Creación de tablas corregidas
CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO INT NOT NULL, 
    DNI VARCHAR(9) NOT NULL UNIQUE,
    NACIONALIDAD VARCHAR(50) NOT NULL,
    SALDO DECIMAL(10,2) DEFAULT 0.0 NOT NULL, 
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CASINO (
    ID_CASINO INT NOT NULL, 
    NOMBRE VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(10) NOT NULL, 
    EMAIL VARCHAR(30) NOT NULL,
    DIRECTOR VARCHAR(12),
    PRIMARY KEY (ID_CASINO), 
    CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE '%_@__%.__%')
);

CREATE TABLE EMPLEADO (
    NSS VARCHAR(12) NOT NULL,
    DNI VARCHAR(9) NOT NULL UNIQUE, 
    NOMBRE VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL, 
    TIPO_CONTRATO VARCHAR(15) NOT NULL, 
    CASINO_TRABAJA INT,
    FECHA_CONTRATACION DATE NOT NULL, 
    DESEMPENO INT,
    COSTE_HORA DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (NSS),
    FOREIGN KEY (CASINO_TRABAJA) REFERENCES CASINO(ID_CASINO) ON DELETE SET NULL
);

ALTER TABLE CASINO ADD CONSTRAINT FK_DIRECTOR FOREIGN KEY (DIRECTOR) REFERENCES EMPLEADO(NSS) ON DELETE SET NULL;

CREATE TABLE VIP (
    ID_VIP INT NOT NULL,
    FECHA_INSCRIPCION DATE NOT NULL,
    REGIMEN_VIP VARCHAR(10) NOT NULL, 
    PTS_ACUMULADOS INT DEFAULT 0 NOT NULL,
    EMPLEADO_INSCRIPCION VARCHAR(12),
    PRIMARY KEY (ID_VIP),
    FOREIGN KEY (EMPLEADO_INSCRIPCION) REFERENCES EMPLEADO(NSS) ON DELETE CASCADE,
    FOREIGN KEY (ID_VIP) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE SALA (
    ID_SALA INT NOT NULL, 
    NOMBRE VARCHAR(20) NOT NULL, 
    LOCALIZACION VARCHAR(10) NOT NULL, 
    CAPACIDAD INT NOT NULL, 
    CASINO_PERTENECE INT, 
    PRIMARY KEY (ID_SALA),
    FOREIGN KEY (CASINO_PERTENECE) REFERENCES CASINO(ID_CASINO) ON DELETE CASCADE
);

-- CORREGIDO: Cambiado SET NULL por CASCADE porque ID_SALA es NOT NULL
CREATE TABLE MESA_JUEGO (
    ID_MESA INT NOT NULL,
    TIPO_JUEGO VARCHAR(20) NOT NULL,
    CAPACIDAD INT NOT NULL, 
    ESTADO VARCHAR(20) NOT NULL, 
    ID_SALA INT NOT NULL, 
    LIMITE_MAX DECIMAL(10,2) NOT NULL,
    LIMITE_MIN DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_MESA),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA) ON DELETE CASCADE, 
    CONSTRAINT CHK_CAPACIDAD CHECK (CAPACIDAD > 4)
);

CREATE TABLE CRUPIER (
    NSS VARCHAR(12) NOT NULL, 
    SUPLENTE VARCHAR(12), 
    PRIMARY KEY (NSS),
    FOREIGN KEY (SUPLENTE) REFERENCES CRUPIER(NSS) ON DELETE SET NULL,
    FOREIGN KEY (NSS) REFERENCES EMPLEADO(NSS) ON DELETE CASCADE 
);

-- CORREGIDO: Cambiado SET NULL por CASCADE porque MESA_ASOCIADA es NOT NULL
CREATE TABLE SESION_MESA (
    ID_SESION INT NOT NULL,
    FECHA_UPDATE DATETIME NOT NULL,
    HORA_APERTURA DATETIME NOT NULL,
    HORA_CIERRE DATETIME NOT NULL,
    CAJA_INICIAL DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
    CAJA_FINAL DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
    MESA_ASOCIADA INT NOT NULL,
    PRIMARY KEY(ID_SESION),
    FOREIGN KEY (MESA_ASOCIADA) REFERENCES MESA_JUEGO(ID_MESA) ON DELETE CASCADE
);

-- CORREGIDO: Cambiado SET NULL por CASCADE en ambas claves
CREATE TABLE REGISTRO_CRUPIERS_SESIONES (
    ID_JORNADA INT NOT NULL,
    HORA_INICIO DATETIME NOT NULL,
    HORA_FIN DATETIME NOT NULL,
    SESION INT NOT NULL,
    EMPLEADO VARCHAR(12) NOT NULL, 
    PRIMARY KEY (ID_JORNADA),
    FOREIGN KEY (SESION) REFERENCES SESION_MESA(ID_SESION) ON DELETE CASCADE,
    FOREIGN KEY (EMPLEADO) REFERENCES CRUPIER(NSS) ON DELETE CASCADE
);

CREATE TABLE EMPLEADO_RECEPCION (
    NSS VARCHAR(12) NOT NULL, 
    PUESTO INT NOT NULL, 
    PRIMARY KEY (NSS),
    FOREIGN KEY (NSS) REFERENCES EMPLEADO(NSS) ON DELETE CASCADE
);

CREATE TABLE TRANSACCION_CAJA (
    ID_TRANSACCION BIGINT NOT NULL,
    TIPO_OPERACION VARCHAR(20) NOT NULL,
    IMPORTE DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
    METODO_PAGO VARCHAR(20) DEFAULT 'EFECTIVO' NOT NULL, 
    FECHA_TRANSACCION DATETIME NOT NULL,
    EMPLEADO_RESPONSABLE VARCHAR(12) NOT NULL,
    CLIENTE_SOLICITANTE INT NOT NULL,
    PRIMARY KEY(ID_TRANSACCION),
    FOREIGN KEY (EMPLEADO_RESPONSABLE) REFERENCES EMPLEADO_RECEPCION(NSS) ON DELETE CASCADE, 
    FOREIGN KEY (CLIENTE_SOLICITANTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE APUESTA (
    ID_APUESTA INT NOT NULL, 
    RESULTADO VARCHAR(20) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DESCRIPCION VARCHAR(50), 
    PRIMARY KEY (ID_APUESTA), 
    CONSTRAINT CHK_VALOR CHECK (VALOR > 1.0) 
);

CREATE TABLE EMPLEADO_ADMINISTRACION (
    NSS VARCHAR(12) NOT NULL,    
    USUARIO VARCHAR(10) NOT NULL, 
    CLAVE VARCHAR(12) NOT NULL, 
    PRIMARY KEY (NSS),
    FOREIGN KEY (NSS) REFERENCES EMPLEADO(NSS) ON DELETE CASCADE
);

CREATE TABLE CASINO_TIENE_CLIENTE (
    ID_CASINO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,  
    PRIMARY KEY (ID_CLIENTE, ID_CASINO),
    FOREIGN KEY (ID_CASINO) REFERENCES CASINO(ID_CASINO) ON DELETE CASCADE, 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE CLIENTE_REALIZA_APUESTA_MESA (
    ID_CLIENTE INT NOT NULL,
    ID_MESA_JUEGO INT NOT NULL, 
    ID_APUESTA INT NOT NULL, 
    PRIMARY KEY (ID_CLIENTE, ID_MESA_JUEGO, ID_APUESTA),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE, 
    FOREIGN KEY (ID_MESA_JUEGO) REFERENCES MESA_JUEGO(ID_MESA) ON DELETE CASCADE, 
    FOREIGN KEY (ID_APUESTA) REFERENCES APUESTA(ID_APUESTA) ON DELETE CASCADE 
);